name: NodeJS with Webpack

on:
  push:
    branches: [ "maya-trenser-action-1" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        yarn install
        npm run build
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: platform/app/dist
        
  deploy:
    environment:
      name: development
      url: https://github.com/${{ github.repository }}/releases/tag/1
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: platform/app/dist
